# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "Character setup eval"

prompts:
  - id: file://../prompts/v5.js
    label: "Character v5"

providers:
  - id: file://../../models/cloud/chat/v6.yaml

defaultTest:
  assert:
    # response must be between 1 and 20 words long
    - type: word-count
      value:
        min: 1
        max: 100
    # no special characters allowed in the response
    - type: not-regex
      value: "[\\[\\]{}|\\\/<>#$&*]"

    - type: llm-rubric
      metric: personality
      provider:
        id: openrouter:openai/gpt-5-mini
        config:
          temperature: 0.2
      value: |
        Does the reply follow the character personality?
        Character description: 
        {{character_description}}

    - type: llm-rubric
      metric: relevance
      provider:
        id: openrouter:openai/gpt-5-mini
        config:
          temperature: 0.2
      value: |
        Does the reply directly address the last user message?
        All messages:
        {{messages}}

    - type: llm-rubric
      metric: hallucination
      provider:
        id: openrouter:openai/gpt-5-mini
        config:
          temperature: 0.2
      value: |
        Does the reply based on the facts that present in the memory, related messages or last messages?
        Memory:
        {{memory}}
        
        Last messages:
        {{messages}}


tests:
  - description: "basic"
    vars:
      character_description: file://basic/character.txt
      messages: file://basic/messages.json

  - description: "memory"
    vars:
      character_description: file://memory/character.txt
      messages: file://memory/messages.json
      memory: file://memory/memory.txt