name: anchovy_chat_ai_bot

x-environment-vars: &environment-vars
  TERM: linux

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      <<: *environment-vars
    env_file:
      - .env
    volumes:
      - .:/proj
      - bot_data:/proj/data
    depends_on:
      - mongo
      - qdrant
    command: python -m src.bot
    restart: always
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27019:27017
    volumes:
      - type: volume
        source: shizo_ded_bot
        target: /data/mongo/shizo_ded_bot_db

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    env_file:
      - .env
    volumes:
      - type: volume
        source: qdrant_data
        target: /qdrant/storage

networks:
  default:
    name: shizo_ded_bot

volumes:
  qdrant_data:
    external: true
  shizo_ded_bot:
    external: true
  bot_data:
    external: true