apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
stringData:
  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
  DATABASE_URL: "${DATABASE_URL}"
  TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
  OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
  QDRANT_URL: "${QDRANT_URL}"
  LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"