# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Image description eval"

prompts:
  - id: file://chat_prompt.json
    label: "Prompt-v1"

providers:
  - file://../models/cloud/image_describe/v1.yaml

defaultTest:
  options:
    transform: JSON.parse(output.replace(/```json|```/g, '').trim())
    provider:
      embedding:
        id: ollama:embedding:mxbai-embed-large
  vars:
    prompt: file://../../src/prompts/image_describe/v1.j2

  assert:
    # json format
    - type: contains-json
      value:
        required:
          - description
          - ocr_text
        type: object

    # Keywords present
    - type: icontains-all
      metric: keyword_coverage
      value: '{{expected.keywords}}'

    #similarity
    - type: similar
      metric: similarity
      transform: output.description
      value: '{{expected.description}}'
      threshold: 0.8

    - type: similar
      metric: similarity
      transform: output.ocr_text
      value: '{{expected.ocr_text}}'
      threshold: 0.9

tests:
  - description: "simple_image"
    vars:
      image: file://images/simple_image.jpg
      expected:
        keywords: [ "мужчина", "офис" ]
        ocr_text: "инвестировал в говно"
        description: "Мужчина в костюме сидит в офисе за столом, на столе надпись 'инвестировал в говно'."

  - description: "screenshot"
    vars:
      image: file://images/screenshot.jpg
      expected:
        keywords: [ "анчоусы", "кентубас", "лоу-таб" ]
        ocr_text: "22:31 Анчоусы 11 members Pinned Message бля че го по 2 часа в день и бимбимбамб... Ален Ищанов @GuldenToktassyn у тебя фронт... Э 10:40 Ален Ищанов @GuldenToktassyn у тебя фронтов и... Лоу-таб эт чё такое? 10:41 Ален Ищанов кентубасик Э Bekniyaz Zhumagulov У меня кентубас работу ищет 10:41 Bekniyaz Zhumagulov 0 прикинь Да ну нах 10:41 Anton Luboshnikov Лоу-таб эт чё такое? Ну типа слабый 10:41 Message Ален Ищанов У меня кентубас работу ищет Ты про меня что ли? 10:41"
        description: "Скриншот чата в Telegram, где участники обсуждают 'лоу-таб' и ищут работу для кентубаса."


