# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Recap eval"

prompts:
  - file://../../src/prompts/recap/v1.j2

providers:
  - file://../models/cloud/recap/v1.yaml
  - file://../models/cloud/recap/v1_01.yaml
  - file://../models/cloud/recap/v1_05.yaml

defaultTest:
  assert:
    - type: javascript # is short enough
      value: 1 - (output.length / context.vars.recap_text.length)

tests:
  - vars:
      recap_text: file://simple_recap/input.txt
      eval_good_sample: file://simple_recap/good_sample.txt
      eval_bad_sample: file://simple_recap/bad_sample.txt

    assert:
      - type: icontains-all # got all keywords
        value:
          - донер
          - парк
          - понедельник
      - type: not-icontains-any # no translated nicknames
        value:
          - Бекниязз
          - Уродчтоли
          - Имдемур
          - Рднул

      - type: llm-rubric
        provider:
          id: ollama:completion:llama3
          config:
            temperature: 0
            top_p: 0.1
        value: |
          You are evaluating a summary.
          
          1. Context Integrity:
            - Does the summary avoid merging unrelated events?
            - Are separate discussions kept separate?
            - Penalize if independent messages are combined into one plan or idea.
          
          2. Faithfulness:
            - No hallucinations or incorrect conclusions.
          
          3. Coverage:
            - Important points are included.
          
          4. Relevance:
            - Excludes unimportant details
          
          Scoring:
            - 1.0 = perfect
            - 0.7 = acceptable
            - 0.4 = major issues
            - 0.0 = incorrect
          
          Return ONLY a number.
          
          Good summary example:
          {{eval_good_sample}}
          
          ---
          Bad summary example:
          {{eval_bad_sample}}
          
          ---
          Original conversation:
          {{recap_text}}
          
          ---