name: Deploy
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long

      - name: Build and push
        id: push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      QDRANT_URL: ${{ secrets.QDRANT_URL }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      BOT_NICKNAME: ${{ vars.BOT_NICKNAME }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      ALLOWED_CHAT_IDS: ${{ vars.ALLOWED_CHAT_IDS }}
      ALLOWED_USER_IDS: ${{ vars.ALLOWED_USER_IDS }}
      RANDOM_REPLY_CHANCE: ${{ vars.RANDOM_REPLY_CHANCE }}
      RANDOM_REPLY_COOLDOWN_MINUTES: ${{ vars.RANDOM_REPLY_COOLDOWN_MINUTES }}
      AI_TIMEOUT: ${{ vars.AI_TIMEOUT }}
      CHAT_RATE_LIMIT: ${{ vars.CHAT_RATE_LIMIT }}
      EMBEDDINGS_SEARCH_MAX_SIZE: ${{ vars.EMBEDDINGS_SEARCH_MAX_SIZE }}
      MESSAGES_EMBEDDINGS_MAX_SIZE: ${{ vars.MESSAGES_EMBEDDINGS_MAX_SIZE }}
      MESSAGES_MEMORY_MAX_SIZE: ${{ vars.MESSAGES_MEMORY_MAX_SIZE }}
      LAST_MESSAGES_SIZE: ${{ vars.LAST_MESSAGES_SIZE }}
      LAST_MESSAGES_MIN_SIZE: ${{ vars.LAST_MESSAGES_MIN_SIZE }}
      ENABLE_MEMORY_PROCESSING: ${{ vars.ENABLE_MEMORY_PROCESSING }}
      RESPOND_MEDIA_PROCESSING_POLLING_TIMEOUT: ${{ vars.RESPOND_MEDIA_PROCESSING_POLLING_TIMEOUT }}
      OPENROUTER_API_URL: ${{ vars.OPENROUTER_API_URL }}
      EMBEDDINGS_MODEL_NAME: ${{ vars.EMBEDDINGS_MODEL_NAME }}
      EMBEDDINGS_VECTOR_SIZE: ${{ vars.EMBEDDINGS_VECTOR_SIZE }}
      LANGSMITH_TRACING: ${{ vars.LANGSMITH_TRACING }}
      LANGSMITH_ENDPOINT: ${{ vars.LANGSMITH_ENDPOINT }}
      LANGSMITH_PROJECT: ${{ vars.LANGSMITH_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install

      - name: Setup k8s
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |-
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl cluster-info

      - name: Lowercase image name
        run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> "$GITHUB_ENV"
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Deploy k8s
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:sha-${{ github.sha }}
        run: ./deploy-k8s.sh